apiVersion: v2
description: A Helm Chat to Deploy Digit Backbone Services
name: backbone-services
version: 2.9.0
appVersion: 2.9.0
dependencies:
  - name: postgres
    version: 0.1.0	
    repository: "file://postgres"
#  - name: cert-manager
#    version: 0.1.0
#    repository: "file://cert-manager"
  - name: redis
    version: 0.1.0
    repository: "file://redis"
  - name: common
    version: 0.0.5
    repository: "file://../common"
